apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# extend base resources
resources:
  - ../../base

namespace: dev

# dev replicas 1
replicas:
  - name: guestbook-ui
    count: 1

images:
  - name: nginx
    newTag: "1.25"
